version: '3'
services:
  ciphertech-ctf:
    build: .
    container_name: datacenter_ghost_challenge
    ports:
      - "8080:8080"
    volumes:
      # This creates a persistent volume so if students restart, 
      # they don't lose their specific queries or changes (optional)
      - ctf_data:/investigation
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  ctf_data:
